ERP.WEB/ERP_WEB/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Infra.Data;
using Application.VM;
using AutoMapper;
using Domain.Entities;
using System.Globalization;
using System.Threading;
using Microsoft.Extensions.Logging;

namespace ERP_WEB.Controllers
{
    public class ComprasController : Controller
    {
        //Para Capitalizar as palavras
        TextInfo ti = CultureInfo.CurrentCulture.TextInfo;


        private readonly ERPDbContext _context;
        private readonly IMapper _mapper;
        private readonly ILogger _logger;

        public ComprasController(ERPDbContext context,
            IMapper mapper,
            ILogger<ComprasController> logger)
        {
            _context = context;
            _mapper = mapper;
            _logger = logger;
        }

        // GET: Produtos
        public async Task<IActionResult> Index()

        {
            
            try
            {
                var comprasVM = new CompraIndexVM()
                {
                    Compras = await _context.Compras.AsNoTracking().ToListAsync()


            };
                

                return View(comprasVM);
            }
            catch (Exception e) {
                _logger.LogInformation($" {e}================GET api/categorias/produtos ======================");

            }
            return View();

        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Compras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CompraCreateVM produtoVM)
        {
            CompraCreateVM produtoCreateVM = new CompraCreateVM()
            {
                Price = produtoVM.Price.Replace('€',' ').Trim(),
                DateTime = produtoVM.DateTime,
                Nome = produtoVM.Nome,
                Fornecedor = produtoVM.Fornecedor,
                Quantidade = produtoVM.Quantidade              
                
            };
            

            if (ModelState.IsValid)
            {
                
                var produto = new Compra
                {
                    
                    Nome = ti.ToTitleCase(produtoVM.Nome.Trim()),
                    DateTime=produtoCreateVM.DateTime,
                    Fornecedor=produtoVM.Fornecedor,
                    Quantidade=produtoVM.Quantidade,
                    Price = decimal.Parse(produtoCreateVM.Price)
                };
                produto.Total=produto.TotalCal(produto.Price, produto.Quantidade);
                _context.Add(produto);
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produtoVM);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            
            
            if (compra == null)
            {
                return NotFound();
            }
            var compraVM = new CompraCreateVM()
            {
                Id=compra.Id,
                Nome = compra.Nome,
                DateTime = compra.DateTime,
                Fornecedor = compra.Fornecedor,
                Price = String.Format($"{compra.Price}").Replace('.',' ').Replace("€", "").Trim(),
                Quantidade = compra.Quantidade

            };
            return View(compraVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CompraCreateVM compraVM)
        {
            if (id != compraVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var dPrice = compraVM.Price.Replace('.', ' ').Replace('€', ' ').Trim();
                    var compra = new Compra
                    {
                        Id= compraVM.Id,
                        Nome = ti.ToTitleCase(compraVM.Nome.Trim()),
                        DateTime = compraVM.DateTime,
                        Fornecedor = compraVM.Fornecedor,
                        Quantidade = compraVM.Quantidade,
                        Price = decimal.Parse(dPrice)
                    };
                    compra.Total = compra.TotalCal(compra.Price, compra.Quantidade);
                    
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(compraVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compraVM);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Compras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produto = await _context.Compras.FindAsync(id);
            _context.Compras.Remove(produto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
            return _context.Compras.Any(e => e.Id == id);
        }
    }
}

ERP.WEB/ERP_WEB/Controllers/ConsumosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Entities;
using Infra.Data;

namespace ERP_WEB.Controllers
{
    public class ConsumosController : Controller
    {
        private readonly ERPDbContext _context;

        public ConsumosController(ERPDbContext context)
        {
            _context = context;
        }

        // GET: Consumos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Consumos.ToListAsync());
        }

        // GET: Consumos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consumo = await _context.Consumos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consumo == null)
            {
                return NotFound();
            }

            return View(consumo);
        }

        // GET: Consumos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Consumos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,DateTime,Quantidade,Id")] Consumo consumo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(consumo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(consumo);
        }

        // GET: Consumos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try { 
            if (id == null)
            {
                return NotFound();
            }

            var consumo = await _context.Consumos.FindAsync(id);
            if (consumo == null)
            {
                return NotFound();
            }
            return View(consumo);
            }catch (Exception ) { }
            return View();
        }

        // POST: Consumos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nome,DateTime,Quantidade,Id")] Consumo consumo)
        {
            if (id != consumo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consumo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsumoExists(consumo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(consumo);
        }

        // GET: Consumos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consumo = await _context.Consumos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consumo == null)
            {
                return NotFound();
            }

            return View(consumo);
        }

        // POST: Consumos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var consumo = await _context.Consumos.FindAsync(id);
            _context.Consumos.Remove(consumo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConsumoExists(int id)
        {
            return _context.Consumos.Any(e => e.Id == id);
        }
    }
}

ERP.WEB/ERP_WEB/Controllers/EstoqueController.cs
using Application.VM;
using Domain.Entities;
using Infra.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;


namespace ERP_WEB.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly ERPDbContext _context;

        public EstoqueController(ERPDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index( )
        {
            //Lista de todas as compras
            var compraList = await _context.Compras.ToListAsync();

            //TO DO Selecionar a lista da tabela produto
            var produtoList = compraList.Select(n => n.Nome).Distinct().ToList();

            var estoqueLista = new List<EstoqueNomeQuantVM>();

            foreach (var prod in produtoList)
            {
                var somaCompra = _context.Compras.Where(n => n.Nome == prod).Sum(n => n.Quantidade);
                var somaConsum = _context.Consumos.Where(n => n.Nome == prod).Sum(n => n.Quantidade);
                
                var estoqueNomeQuantVM = new EstoqueNomeQuantVM()
                {
                    Nome = prod,
                    Quantidade = somaCompra-somaConsum
                };

                estoqueLista.Add(estoqueNomeQuantVM);
            }

            return View(estoqueLista.ToList());
        }


    }
}

ERP.WEB/ERP_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ERP_WEB</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />*@


     <environment include="Development">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

        <!-- IonIcons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

        
        <link rel="stylesheet" href="~/assets_develop/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

        <link rel="stylesheet" href="~/assets/css/site.min.css" />
    </environment>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ERP_WEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consumos" asp-action="Index">Consumo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoque" asp-action="Index">Estoque</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ERP_WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/assets_develop/js/jquery.js" type="text/javascript"></script>
        <script src="~/assets_develop/js/jquery.maskMoney.js" type="text/javascript" ></script>
        <script src="~/assets_develop/js/site.js" asp-append-version="true"></script>
        
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js" type="text/javascript"></script>
        
       
     </environment>
    <environment exclude="Development">
        <script src="~/assets/js/jquery.min.js" type="text/javascript"></script>
        <script src="~/assets/js/jquery.maskMoney.min.js" type="text/javascript"></script>
        <script src="~/assets/js/site.min.js" type="text/javascript" asp-append-version="true"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
        
        
    </environment>
     @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
    <script>
        
        $(function() {
            $("#Price").maskMoney({thousands:'.', decimal:',', allowZero:true, suffix: ' €'});
        })

    </script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>